# Generated by Django 4.2.27 on 2025-12-22 04:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year value (e.g., 2025)', unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='years_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='core.year')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
                'ordering': ['-year__year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FinReportSnapshot',
            fields=[
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fin_report', serialize=False, to='core.month')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Total income for the month', max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Total expenses for the month', max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Net profit (income - expenses)', max_digits=12)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Operating expenses', max_digits=12)),
                ('marketing_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Marketing and advertising expenses', max_digits=12)),
                ('payroll_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Payroll and HR expenses', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_reports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Report Snapshot',
                'verbose_name_plural': 'Financial Report Snapshots',
            },
        ),
        migrations.CreateModel(
            name='DeliveryReportSnapshot',
            fields=[
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery_report', serialize=False, to='core.month')),
                ('total_deliveries', models.IntegerField(default=0, help_text='Total number of deliveries', validators=[django.core.validators.MinValueValidator(0)])),
                ('on_time_deliveries', models.IntegerField(default=0, help_text='Number of on-time deliveries', validators=[django.core.validators.MinValueValidator(0)])),
                ('late_deliveries', models.IntegerField(default=0, help_text='Number of late deliveries', validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_accuracy', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery accuracy percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue from deliveries', max_digits=12)),
                ('delivery_costs', models.DecimalField(decimal_places=2, default=0.0, help_text='Total delivery costs', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_reports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Report Snapshot',
                'verbose_name_plural': 'Delivery Report Snapshots',
            },
        ),
    ]
