# Generated by Django 4.2.27 on 2025-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreportsnapshot',
            name='delivery_accuracy',
        ),
        migrations.RemoveField(
            model_name='deliveryreportsnapshot',
            name='delivery_costs',
        ),
        migrations.RemoveField(
            model_name='deliveryreportsnapshot',
            name='late_deliveries',
        ),
        migrations.RemoveField(
            model_name='deliveryreportsnapshot',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='deliveryreportsnapshot',
            name='on_time_deliveries',
        ),
        migrations.RemoveField(
            model_name='deliveryreportsnapshot',
            name='total_deliveries',
        ),
        migrations.RemoveField(
            model_name='deliveryreportsnapshot',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='finreportsnapshot',
            name='marketing_expenses',
        ),
        migrations.RemoveField(
            model_name='finreportsnapshot',
            name='net_profit',
        ),
        migrations.RemoveField(
            model_name='finreportsnapshot',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='finreportsnapshot',
            name='operating_expenses',
        ),
        migrations.RemoveField(
            model_name='finreportsnapshot',
            name='payroll_expenses',
        ),
        migrations.RemoveField(
            model_name='finreportsnapshot',
            name='total_expenses',
        ),
        migrations.RemoveField(
            model_name='finreportsnapshot',
            name='total_income',
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='av_rate_h',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='av_salary_h',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_income_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_income_outsourcing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_income_outstaffing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_income_per_employee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_income_tm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_revenue_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_revenue_outsourcing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_revenue_outstaffing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_revenue_tm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='avg_salary_prod',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='base_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='billability',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='billability_fp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='billability_outsourcing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='billability_outstaffing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='billability_tm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='billable_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='fte',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='gm_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='gp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='gp_fte_h',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='project_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='pto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='rev_prod_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='revenue_growth_mtm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='salary_growth_mtm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='total_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='utilization_excl_pto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreportsnapshot',
            name='utilization_incl_pto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='accrual_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='accrual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='cash_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='cogs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='dividends_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='dividends_to_be_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='emergency_fund_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='emergency_fund_saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='emergency_fund_to_be_saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='gross_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='income_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='net_margin_before_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='net_margin_before_tax_jira',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='net_margin_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='overhead',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='overhead_by_fte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='paid_dividends',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='production_team_fte',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finreportsnapshot',
            name='sales_commissions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
