# Generated by Django 4.2.27 on 2025-12-23 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_deliveryreportsnapshot_delivery_accuracy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Delivery Report')", max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this report contains')),
                ('icon', models.CharField(default='📊', help_text='Emoji or icon identifier', max_length=50)),
                ('is_system', models.BooleanField(default=False, help_text='System report types cannot be edited or deleted')),
                ('parsing_config', models.JSONField(default=dict, help_text='\n        Configuration for CSV parsing. Example:\n        {\n            "format": "transposed",  # or "normal"\n            "header_row": 1,  # which row (0-indexed) contains column headers\n            "data_start_row": 2,  # which row data starts\n            "month_column_type": "names",  # "names" (January, February) or "numbers" (1, 2, 3)\n            "field_mappings": {\n                "CSV Column Name": {\n                    "field": "database_field_name",\n                    "type": "decimal",  # or "integer", "percentage", "string"\n                    "required": false\n                }\n            }\n        }\n        ')),
                ('field_schema', models.JSONField(default=dict, help_text='\n        Schema defining all fields. Example:\n        {\n            "revenue": {\n                "label": "Revenue",\n                "type": "decimal",\n                "format": "$0,0.00",\n                "description": "Total revenue for the month"\n            },\n            "fte": {\n                "label": "FTE",\n                "type": "integer",\n                "description": "Full-time equivalent employees"\n            }\n        }\n        ')),
                ('display_config', models.JSONField(default=dict, help_text='\n        Configuration for displaying data. Example:\n        {\n            "table_columns": ["month", "revenue", "fte"],\n            "summary_fields": ["total_revenue", "avg_fte"],\n            "charts": [\n                {\n                    "type": "line",\n                    "title": "Revenue Trend",\n                    "y_axis": ["revenue"]\n                }\n            ]\n        }\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Type',
                'verbose_name_plural': 'Report Types',
                'ordering': ['is_system', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='\n        Report data stored as key-value pairs. Example:\n        {\n            "revenue": 1000.50,\n            "fte": 14,\n            "utilization": 85.5,\n            "custom_metric": "some value"\n        }\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.month')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.year')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-year__year', '-month__month'],
                'indexes': [models.Index(fields=['report_type', 'year', 'month'], name='reports_rep_report__8e927d_idx')],
                'unique_together': {('report_type', 'year', 'month')},
            },
        ),
    ]
